### ISSUE TITLE
Why is foo@bar allowed?

### ISSUE THREAD

**Issue by JanisE** [sindresorhus/email-regex#7]
Why is foo@bar allowed? Is that really a valid e-mail address?

**Comment by sindresorhus** [comment]
Yup => https://stackoverflow.com/a/20573804/64949

**Comment by JanisE** [comment]
Oh, thanks! I will probably adjust the regexp to not allow dev environments though.

**Comment by sindresorhus** [comment]
Happy to add an option for that if someone does a PR with tests and docs.

**Comment by niftylettuce** [comment]
I have published <https://github.com/niftylettuce/email-regex-safe> as an alternative to this package, with a lot of configurable options.  PR's welcome.

**Comment by monolithed** [comment]
Dotless domains have been prohibited since 2013 
https://archive.icann.org/historical-resolution-tracking-feature/dotless-domains.html
https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-meeting-of-the-new-gtld-program-committee-13-08-2013-en#1.a
https://lists.icann.org/hyperkitty/list/bc-gnso@icann.org/thread/H6UQGJDVZCHVASOGVGJBHLBMUS2GZXGO/
